version: 2
jobs:
  build:
    docker:
      - image: cimg/node:20.19.2
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:hR5VSxbpQUjrD8hK1Mvfhl1jg8E0ywm7ICkqp6zgHu"
       - checkout
      - restore_cache:
          keys:
            - dependencies_circle_demo
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies_circle_demo
      - run:
          name: Build
          command: yarn build
      - run:
          name: Prepare shell commands
          command: chmod +x deploy.sh
      - run:
          name: Run Deploy to Github pages
          command: ./deploy.sh
